name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set the date value
        run: echo "IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/test-image:$(date +%s)" >> $GITHUB_ENV
      - name: Build the Docker image
        run: docker build -t ${{ env.IMAGE_NAME }} .
      - name: Output DATE for next job
        id: step3
        run: echo "IMAGE_NAME=${{ env.IMAGE_NAME }}" >> $GITHUB_OUTPUT
      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Push the image
        run: docker push ${{ env.IMAGE_NAME }}
      - name: Set git config
        run: |
          git config --unset-all http.https://github.com/.extraheader 
          git config set user.email "dorattar4@gmail.com"
          git config set user.name "shmador"
          git config pull.rebase false
      - name: Clone test-repo
        run: git clone https://shmador:${{ secrets.ACCESS_TOKEN }}@github.com/shapi78/test-repo.git && cd test-repo
      - name: Set branch
        run: git checkout -b dor_docker
      - name: Add version file
        run: | 
          echo ${{ env.IMAGE_NAME }} > latest_image.txt
          git add latest_image.txt
          git commit -m "Updated the latest_image.txt, from GitHub actions automation on another repository"
      - name: Pull current branch
        run: git pull https://shmador:${{ secrets.ACCESS_TOKEN }}@github.com/shapi78/test-repo.git dor_docker
      - name: Push to GitHub
        run: git push --set-upstream https://shmador:${{ secrets.ACCESS_TOKEN }}@github.com/shapi78/test-repo.git dor_docker
