name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step3.outputs.IMAGE_NAME }}
    steps:
      - uses: actions/checkout@v4
      - name: Set the date value
        run: echo "IMAGE_NAME=shmador/test-image:$(date +%s)" >> $GITHUB_ENV
      - name: Build the Docker image
        run: docker build -t ${{ env.IMAGE_NAME }} .
      - name: Output DATE for next job
        id: step3
        run: echo "IMAGE_NAME=${{ env.IMAGE_NAME }}" >> $GITHUB_OUTPUT
  push:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Push the image
        run: docker push ${{needs.build.outputs.output1}}
