name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set the date value
        run: echo "IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/test-image:$(date +%s)" >> $GITHUB_ENV
      - name: Build the Docker image
        run: docker build -t ${{ env.IMAGE_NAME }} .
      - name: Output DATE for next job
        id: step3
        run: echo "IMAGE_NAME=${{ env.IMAGE_NAME }}" >> $GITHUB_OUTPUT
      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Push the image
        run: docker push ${{ env.IMAGE_NAME }}
      - name: Set git config
        run: | 
          git config set --global user.email "dorattar4@gmail.com"
          git config set --global user.name "shmador"
      - name: Clone test-repo
        run: git clone git@github.com:shapi78/test-repo.git && cd test-repo
      - name: Set branch
        run: git checkout dor_docker
      - name: Add version file
        run: | 
          echo ${{ env.IMAGE_NAME }} > latest_image.txt
          git add latest_image.txt
          git commit -m "Updated the latest_image.txt, from GitHub actions automation on another repository"
      - name: Push to GitHub
        run: git push origin dor_docker
