name: Docker Image CI

on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Generate tag for the image
      run: echo "IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/test-image:$(date +%s)" >> $GITHUB_ENV
    - name: Build the Docker image
      run: docker build -t $IMAGE_NAME .
    - name: Log in to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Push the image
      run: docker push $IMAGE_NAME
